# Generated by Django 3.2.12 on 2023-03-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('draft', 'draft'), ('published', 'published')], default='draft', max_length=9)),
            ],
        ),
    ]
